Add throttling to error e-mails
VEuPathDB/EbrcWebsiteCommon pull request #208
Opened 2023-03-10 14:56 UTC by dmgaldi

## Overview
Added throttling for error e-mails.

Things I'm unsure about:
* Should throttling config be moved to model config?
* E-mail contents and subject line. Maybe they should be more consistent with error emails?

## Testing
* Set throttling on my dev site to burst size of 1 and verified a single error e-mail came through.

2023-03-10 20:03 UTC, ryanrdoherty requested changes
Added that one comment + our discussion about converting to a non-static class.

2023-03-13 19:56 UTC, ryanrdoherty requested changes

2023-03-13 22:11 UTC, dmgaldi commented on Model/src/main/java/org/eupathdb/common/errors/ErrorEmailThrottler.java
> +  private static final String WDK_PROP_EMAIL_SUSTAINED_THROTTLE_KEY= "EMAIL_SUSTAINED_THROTTLE_RATE_PER_SECOND";
That's correct. We want to fill the bucket once every 10 minutes. Would you prefer the units to be specified as per minute or hour and the converted when passed to the underlying rate limiter?

2023-03-13 22:13 UTC, dmgaldi commented on Model/src/main/java/org/eupathdb/common/errors/ErrorEmailThrottler.java
> +    scheduledExecutorService.scheduleAtFixedRate(this::sendThrottlingReport, 0L, 1, TimeUnit.HOURS);
Theoretically, yes when tomcat is shutdown we should gracefully close this. Where would this belong on the site lifecycle? In `EuPathSiteSetup` called by `ApplicationInitListener`?

2023-03-14 02:47 UTC, ryanrdoherty commented on Model/src/main/java/org/eupathdb/common/errors/ErrorEmailThrottler.java
> +  private static final String WDK_PROP_EMAIL_SUSTAINED_THROTTLE_KEY= "EMAIL_SUSTAINED_THROTTLE_RATE_PER_SECOND";
So the units added in the "rate per second" is not "permits" but "burst size permits" i.e. "fills"?  If this is correct, then the actual fill rate depends on both the burst size and the throttle rate?  This seems more confusing to me than simply using "permits" as the units for both and having them be independent (total size and # added per second).  Maybe I'm still just thinking about this all wrong?

2023-03-14 14:18 UTC, ryanrdoherty commented on Model/src/main/java/org/eupathdb/common/errors/ErrorEmailThrottler.java
> +    scheduledExecutorService.scheduleAtFixedRate(this::sendThrottlingReport, 0L, 1, TimeUnit.HOURS);
Let's meet about this.  Thinking of two ways to do it and we can decide together which one is better.

2023-03-15 15:41 UTC, merged